import logo from "../assets/img/logo.png";
import glogo from "../assets/img/google.png";
import banner from "../assets/img/bannerl.webp";
import comingsoon from "../assets/img/coming-soon.jpg";
import settingimg1 from "../assets/img/settingimg1.png";
import settingimg2 from "../assets/img/settingimg2.png";
import settingimg3 from "../assets/img/settingimg3.png";
import settingimg4 from "../assets/img/settingimg4.png";
import settingimg5 from "../assets/img/settingimg5.png";
import settingimg6 from "../assets/img/settingimg6.png";
import settingimg7 from "../assets/img/settingimg7.png";
import settingimg8 from "../assets/img/settingimg8.png";
import settingimg9 from "../assets/img/settingimg9.png";
import settingimg10 from "../assets/img/settingimg10.png";
import settingimg11 from "../assets/img/settingimg11.png";
import settingimg12 from "../assets/img/settingimg12.png";
import settingimg13 from "../assets/img/settingimg13.png";
import random01 from "../assets/img/random-01.svg";
import random02 from "../assets/img/random-02.svg";
import random03 from "../assets/img/random-03.svg";
import random04 from "../assets/img/random-04.svg";
import random05 from "../assets/img/random-05.svg";
import random07 from "../assets/img/random-07.svg";
import trainingschedule from "../assets/img/traning_sedu.png";
import training1 from "../assets/img/training.png";
import registerwap from "../assets/img/registerwap.webp";
import bannre1 from "../assets/img/img1.jpg";
import bannre3 from "../assets/img/img3.jpg";
import bannre4 from "../assets/img/img4.jpg";
import bannre5 from "../assets/img/img5.jpg";

export const loginbanner1 = bannre1;
export const loginbanner3 = bannre3;
export const loginbanner4 = bannre4;
export const loginbanner5 = bannre5;
export const loginbanner = banner;
export const registerbanner = registerwap;
export const google = glogo;
export const sidebarlogo = logo;
export const comingSoonBanner = comingsoon;
export const Settingsimg1 = settingimg1;
export const Settingsimg2 = settingimg2;
export const Settingsimg3 = settingimg3;
export const Settingsimg4 = settingimg4;
export const Settingsimg5 = settingimg5;
export const Settingsimg6 = settingimg6;
export const Settingsimg7 = settingimg7;
export const Settingsimg8 = settingimg8;
export const Settingsimg9 = settingimg9;
export const Settingsimg10 = settingimg10;
export const Settingsimg11 = settingimg11;
export const Settingsimg12 = settingimg12;
export const Settingsimg13 = settingimg13;
export const Random01 = random01;
export const Random02 = random02;
export const Random03 = random03;
export const Random04 = random04;
export const Random05 = random05;
export const Random07 = random07;
export const TrainingSchedule = trainingschedule;
export const Training1 = training1;
